import { getNoticia } from "@/lib/noticias";
import Link from "next/link";
import React from "react";
import DOMPurify from "isomorphic-dompurify";
import { Metadata } from "next/types";
import { unstable_cache } from "next/cache";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {
    "Content-Security-Policy":
      "default-src 'self'; frame-src 'self' www.youtube.com youtube.com; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https: *;",
  },
};

const page = async ({ params }: { params: { id: string } }) => {
  const getCatchedNew = unstable_cache(getNoticia, [params.id], {
    tags: ["noticias"],
  });
  const noticia = await getCatchedNew(params.id);

  const config = {
    ADD_TAGS: ["iframe"],
    ADD_ATTR: [
      "allow",
      "allowfullscreen",
      "frameborder",
      "scrolling",
      "src",
      "width",
      "height",
      "title",
      "referrerpolicy",
      // img attributes
      "alt",
      "loading",
      "style",
      // general attributes for all elements
      "class",
    ],
  };

  const sanitizedHtml = DOMPurify.sanitize(noticia.text2, config);

  console.log(noticia);

  function helper(string: string) {
    while (string.indexOf("<p>&nbsp;</p>") !== -1) {
      string = string.replace("<p>&nbsp;</p>", "");
    }
    return string;
  }

  const parsed = helper(sanitizedHtml);

  return (
    <div className="p-10">
      {noticia.titulo}
      <Link className="block" href={"/"}>
        ← go back
      </Link>
      <div className="grid gap-4">
        <div
          className="wysiwyg max-w-7xl mx-auto bg-slate-900 p-3"
          dangerouslySetInnerHTML={{ __html: parsed }}
        />
      </div>
    </div>
  );
};

export default page;
